version: 2
updates:
- package-ecosystem: bundler
  directory: "/Ruby/exercises"
  target-branch: "develop"
  schedule:
    interval: daily
    time: "12:00"
    timezone: "Asia/Tokyo"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/Ruby/progate/rails5_study_1/tweet_app"
  target-branch: "develop"
  schedule:
    interval: daily
    time: "12:00"
    timezone: "Asia/Tokyo"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/Ruby/progate/rails5_study_2/tweet_app"
  target-branch: "develop"
  schedule:
    interval: daily
    time: "12:00"
    timezone: "Asia/Tokyo"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/Ruby/progate/rails5_study_3/tweet_app"
  target-branch: "develop"
  schedule:
    interval: daily
    time: "12:00"
    timezone: "Asia/Tokyo"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/Ruby/progate/rails5_study_4/tweet_app"
  target-branch: "develop"
  schedule:
    interval: daily
    time: "12:00"
    timezone: "Asia/Tokyo"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/Ruby/progate/rails5_study_5/tweet_app"
  target-branch: "develop"
  schedule:
    interval: daily
    time: "12:00"
    timezone: "Asia/Tokyo"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/Ruby/progate/rails5_study_6/tweet_app"
  target-branch: "develop"
  schedule:
    interval: daily
    time: "12:00"
    timezone: "Asia/Tokyo"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/Ruby/progate/rails5_study_7/tweet_app"
  target-branch: "develop"
  schedule:
    interval: daily
    time: "12:00"
    timezone: "Asia/Tokyo"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/Ruby/progate/rails5_study_8/tweet_app"
  target-branch: "develop"
  schedule:
    interval: daily
    time: "12:00"
    timezone: "Asia/Tokyo"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/Ruby/progate/rails5_study_9/tweet_app"
  target-branch: "develop"
  schedule:
    interval: daily
    time: "12:00"
    timezone: "Asia/Tokyo"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/Ruby/progate/rails5_dojo_1/tweet_app"
  target-branch: "develop"
  schedule:
    interval: daily
    time: "12:00"
    timezone: "Asia/Tokyo"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/Ruby/progate/rails5_dojo_2/tweet_app"
  target-branch: "develop"
  schedule:
    interval: daily
    time: "12:00"
    timezone: "Asia/Tokyo"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/Ruby/progate/rails5_dojo_3/tweet_app"
  target-branch: "develop"
  schedule:
    interval: daily
    time: "12:00"
    timezone: "Asia/Tokyo"
  open-pull-requests-limit: 10