
version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8880:80
    depends_on:
      - app
    volumes:
      - ./quiz/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./quiz/web:/var/www/html
      - ./quiz/web:/usr/share/nginx/html
  app:
    container_name: php_program
    image: php:7.4-fpm
    depends_on:
      - db
    volumes:
      - ./quiz/php/php.ini:/usr/local/etc/php/php.ini
      - ./quiz/web:/var/www/html
      - ./quiz/web:/usr/share/nginx/html
  db:
    container_name: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./quiz/mysql/data:/var/lib/mysql
      - ./quiz/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: quiz
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root-pass
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: pass
